#!/data/data/com.termux/files/usr/bin/bash

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# Fix loadavg
uptime | grep -Po "average: \K.+"| awk -F", " '{ print $1,$2,$3 }' > $tmp/loadavg

# get load averages
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(cat $tmp/loadavg)
# get free memory
IFS=" " read USED AVAIL TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$7,$2'})
# get processes
PROCESS=$(ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }')
PROCESS_ALL=$(echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')
PROCESS_ROOT=$(echo "su -c ${PROCESS}"| grep root | awk {'print $2'})
PROCESS_USER=$(echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')
# get processors
PROCESSOR_NAME=$(grep "model name" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1)
PROCESSOR_COUNT=$(grep -ioP 'processor\t:' /proc/cpuinfo | wc -l)

if [[ -d /system/app/ && -d /system/priv-app ]]; then
    DISTRO="Android $(getprop ro.build.version.release)"
    MODEL="$(getprop ro.product.brand) $(getprop ro.product.model)"
fi

# get public IP address
PUBIP=$(curl -s ifconfig.me)
TSIP=$(2>/dev/null ifconfig | grep -A 1  "tun0" | grep "inet" | cut -c 14- | cut -c -15)
PRIVIP=$(2>/dev/null ifconfig | grep inet | tail -1 | awk '{print $2}')

P="\e[1;95m"
W="\e[0;39m"
G="\e[1;32m"
C="\e[1;36m"
BOLD='\033[1m'


echo -e "
${W}${BOLD}System Info:

$C$BOLD  Host      : $P$MODEL
$P$BOLD  Distro    : $C$DISTRO
$C$BOLD  Kernel    : $P$(uname -sr)

$P$BOLD  Uptime    : $C$(uptime -p)
$C$BOLD  Load      : $G$LOAD1$P (1m), $G$LOAD5$P (5m), $G$LOAD15$P (15>
$P$BOLD  Processes : $G$PROCESS_USER$C (user), $G$PROCESS_ALL$C (total)

$C$BOLD  CPU       : $P$PROCESSOR_NAME ($G$PROCESSOR_COUNT$P vCPU)
$P$BOLD  Memory    : $G$USED$C used, $G$AVAIL$C avail, $G$TOTAL$C tota>

$C$BOLD  PubIP     : $W$PUBIP$W
$P$BOLD  TailIP    : $W$TSIP$W
$C$NOLD  WlanIP    : $W$PRIVIP$W
"  


